# version: '3.8'

# services:
#   web:
#     build: .
#     ports:
#       - "5000:5000"
#     depends_on:
#       - redis

#   redis:
#     image: "redis:alpine"
#     ports:
#       - "6379:6379"
version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:6666"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    