version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /mnt/c/Users/22258/Desktop/timestamp_files:/app/timestamp_files  # 将宿主机桌面目录映射到容器
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
